### ISSUE TITLE
Printing symbols in a matrix

### ISSUE THREAD

**Issue by amitai-hoze** [Daniel-Diaz/HaTeX#59]
Hi, how can I print a matrix with symbols?

I'm using this code:

```haskell
import Text.LaTeX
import Text.LaTeX.Base.Pretty
import Text.LaTeX.Packages.AMSMath
import Data.Matrix

table = [["a","","","",""],["","b","","",""],["","","c","","d"],["","","","a",""],["","","d","","e"]]

matrices :: Monad m => LaTeXT_ m
matrices = pmatrix Nothing $ (fromLists table)

main :: IO ()
main = putStrLn (execLaTeXT matrices >>= prettyLaTeX)
```

and I'm getting:
```latex
\begin{pmatrix}
    \left[ `a`\right] &\left[ \right] &\left[ \right]
    &\left[ \right] &\left[ \right] \\\left[ \right] &\left[
    `b`\right] &\left[ \right] &\left[ \right] &\left[
    \right] \\\left[ \right] &\left[ \right] &\left[
    `c`\right] &\left[ \right] &\left[ `d`\right] \\\left[
    \right] &\left[ \right] &\left[ \right] &\left[
    `a`\right] &\left[ \right] \\\left[ \right] &\left[
    \right] &\left[ `d`\right] &\left[ \right] &\left[
    `e`\right] \\
\end{pmatrix} 
```
But what I want is:
```latex
\begin{pmatrix}
  a &  &  &  &  \\
   & b &  &  &  \\
   &  & c &  & d \\
   &  &  & a &  \\
   &  & d &  & e \\
\end{pmatrix}
```

**Comment by Daniel-Diaz** [comment]
This happens because ``String = [Char]`` and so it is printing the elements of the matrix as list of characters. If your matrix is composed of values of type ``Text``, I believe you'll get the output you are looking for. Just add ``{-# LANGUAGE OverloadedStrings #-}`` at the top of your script, and include the type signature for ``table``, indicating the type  ``[[Text]]``. Not completely sure right now, but you might need to ``import Data.Text (Text)``.

**Comment by amitai-hoze** [comment]
It worked, thanks alot!! :+1: 

P.S.
I didn't need to `import Data.Text (Text)`.

**Comment by joecefnhedog** [comment]
If I had a matrix like:
 (   "L" "M_R" )
( "M_R" "L_R" )

how could I get this to latex without it inserting {} between spaces.
so this is what i'm getting;

\begin{pmatrix}L&\$M\_{}R\$\\\$M\_{}R\$&\$\$L\_{}R\$\$\\\end{pmatrix}
