### ISSUE TITLE
Semigroup instance for LaTeX

### ISSUE THREAD

**Issue by siddharthist** [Daniel-Diaz/HaTeX#92]
I use ClassyPrelude, which exports `(<>)` from `Semigroup`, rather than from `Monoid`. As such, when using HaTeX, I have to use some import trickery:
```haskell
import ClassyPrelude hiding ((<>))
import Text.LaTeX ((<>))
```
It would be much cleaner to just have a `Semigroup LaTeX` instance in this library. While this may sound like a me problem, [there are some pretty good reasons to use Semigroups](http://stackoverflow.com/questions/40688352/why-prefer-monoids-over-semigroups-in-haskell-why-do-we-need-mempty#40688427).

Since `Semigroup` is a superclass of `Monoid`, this would be a very easy two-line addition, and I'm happy to make a pull request:
```haskell
instance Semigroup LaTeX where
  (<>) = mappend
```
For more information about Semigroups (if you're not familiar), here is a blog post: http://philipnilsson.github.io/Badness10k/posts/2016-07-14-functional-patterns-semigroup.html

Thoughts?

**Comment by Daniel-Diaz** [comment]
I added a Semigroup instance: https://github.com/Daniel-Diaz/HaTeX/commit/10a22a07972f730926d8241cd4cb244c30d645b3.

However, note that `Semigroup` is _not_ a superclass of `Monoid`. Perhaps you meant to say that every type that is an instance of `Monoid` can be made an instance of `Semigroup`, but `Monoid` isn't defined as a subclass of `Semigroup` (as of base-4.9.0.0). So the `<>` operator can't be shared, and the monoid version will stay as the operator exported by HaTeX.

Thanks.

**Comment by leftaroundabout** [comment]
But is that reason enough to keep exporting the monoid-restricted `<>`? Question is, for what purpose does `Text.LaTeX` export that anyway – if _only for combining LaTeX_, then the semigroup version would work just as well. If it's supposed to be as a simple prelude-like import for general stuff which might break with `Semigroup`, then I'd say this is not such a good idea anyway.

Could we perhaps somehow deprecate that export?

**Comment by siddharthist** [comment]
@Daniel-Diaz Yes, you're right. I meant _conceptual_ superclass, but of course the typeclass hierarchy doesn't exactly match the mathematical one.

**Comment by Daniel-Diaz** [comment]
@leftaroundabout 

The reason to export `<>` from `Text.LaTeX` was to make this module enough to start using HaTeX. Since `<>` is a very basic combinator of `LaTeX` values, I think it should be exported. Of course, this is just my opinion and it's debatable.

It is unfortunate that we have two versions of `<>` in `base`, and I hope this situation will get solved in the future. If we decided to export the `Semigroup` version of `<>`, then this same issue will hit people having the `Monoid` version of `<>` in scope. So I decided that I would keep exporting the same one to allow code that compiles today to keep compiling without changes.
